<a href="https://colab.research.google.com/github/keisycascante/QM206/blob/main/Clase02-QM206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Arithmetic Operators

In [ ]:
print(8+9)
print(16//2)
print(16/2)
print(4-2)
print(2*2)
print(95%100)
print(2**3)

17
8
8.0
2
4
95
8


Python Arithmetic Operators

Módulo=Residuo

In [ ]:
x=4
x*=6
print(x)
x=7
x%=5
print(x)
x=9
x//=2
print(x)
x=5
x**=3
print(x)

24
2
4
125


In [ ]:
x=5
a=x**3
print(a)
print(x)

125
5


In [ ]:
datos=("apple","bananas","cherry")
print(type(datos))
thislist=list(datos)
print(type(thislist))

<class 'tuple'>
<class 'list'>


In [1]:
estudiantes=["Juan", "Mario","Joaquín"]
print(estudiantes)
estudiantes.append("María")
print(estudiantes)
estudiantes.insert(2,"Lara")
print(estudiantes)
profesores=("Pedro", "Doris", "Vielka")
estudiantes.extend(profesores)
print(estudiantes)
estudiantes.remove("Pedro")
print(estudiantes)
estudiantes.pop(1)
print(estudiantes)

['Juan', 'Mario', 'Joaquín']
['Juan', 'Mario', 'Joaquín', 'María']
['Juan', 'Mario', 'Lara', 'Joaquín', 'María']
['Juan', 'Mario', 'Lara', 'Joaquín', 'María', 'Pedro', 'Doris', 'Vielka']
['Juan', 'Mario', 'Lara', 'Joaquín', 'María', 'Doris', 'Vielka']
['Juan', 'Lara', 'Joaquín', 'María', 'Doris', 'Vielka']


In [ ]:
thislist=["apple","banana","kiwi"]
print(thislist)
for x in thislist:
    print("I like", x)
print(x, "it´s a fruit")
print("Se ha terminado la lista")

['apple', 'banana', 'kiwi']
I like apple
I like banana
I like kiwi
kiwi it´s a fruit
Se ha terminado la lista


In [ ]:
xs=[2,3,4,5,6]
for a in xs:
  b=a*5
print(b)

30


In [ ]:
notas=[4.8,4.2,2.8,3.5]
suma=0
n=len(notas)
for x in notas:
  suma+=x
print("suma", suma)
if n!=0:
  promedio=suma/n
  print("promedio", promedio)
else:
  print("no hay notas")


suma 15.3
promedio 3.825


In [ ]:
notas=[]
suma=0
n=len(notas)
for x in notas:
  suma+=x
print("suma", suma)
if n!=0:
  promedio=suma/n
  print("promedio", promedio)
else:
  print("no hay notas")

suma 0
no hay notas


In [ ]:
a=1
b=2
c=-1
if 4*a*c<b**2:
  x1=(-b+(b**2-4*a*c)**0.5)/(2*a)
  x2=(-b-(b**2-4*a*c)**0.5)/(2*a)
  print("x1", x1)
  print("x2", x2)
else:
  print("no hay raíces reales")

x1 0.41421356237309515
x2 -2.414213562373095


In [ ]:
a=1
b=2
c=1
if 4*a*c<b**2:
  x1=(-b+(b**2-4*a*c)**0.5)/(2*a)
  x2=(-b-(b**2-4*a*c)**0.5)/(2*a)
  print("x1", x1)
  print("x2", x2)
else:
  print("no hay raíces reales")

no hay raíces reales


In [ ]:
thislist=["apple", "kiwi", "cherry"]
mylist=thislist.copy()
mylist[0]="orange"
print(thislist)
print(mylist)

['apple', 'kiwi', 'cherry']
['orange', 'kiwi', 'cherry']


In [ ]:
list1=["a", "b", "c"]
list2=[]

In [ ]:
fruits=["cherry", "banana", "apple", "cherry"]

x=fruits.count("cherry")
print(x)
n=fruits.index("cherry")
print(n)

2
0


In [4]:
import numpy as np

x=8.7
s=np.sqrt(x)
print(s)
v=np.exp(x)
print(v)

2.949576240750525
6002.912217261018


In [ ]:
x=np.array([3.4,6.7,8.9,2.6])
for a in x:
  print(a,np.exp(a))

3.4 29.96410004739701
6.7 812.4058251675433
8.9 7331.973539155995
2.6 13.463738035001692


In [ ]:
x=np.zeros(10)
print(x)
x[3]=5
print(x)
x=np.ones(20)
print(x)
x[5]=6
print(x)
print(np.log(x))
print(np.log10(x))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 6. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.         0.         0.         0.         0.         1.79175947
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.        ]
[0.         0.         0.         0.         0.         0.77815125
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.        ]


In [5]:
x=np.array([0.0,3.4,6.7,8.9,2.6,-3.5])
for a in x:
  print(a,np.exp(a))

0.0 1.0
3.4 29.96410004739701
6.7 812.4058251675433
8.9 7331.973539155995
2.6 13.463738035001692
-3.5 0.0301973834223185


In [ ]:
x=np.zeros(10)
print(x)
x[3]=5
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]


In [ ]:
v=np.ones(200)
v=v+3
print(v*v)

[16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16.]


In [6]:
x=np.linspace(1, 5,5)
y=3.0*np.exp(-x/5)


print(np.sum(x))
print(np.mean(x))
print(np.log(x))
print(np.log10(x))

15.0
3.0
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [7]:
cH=np.array([1.5E-4,6.7E-7,8.9E-2])
pH=-np.log10(cH)
print(pH)

[3.82390874 6.1739252  1.05060999]
