<a href="https://colab.research.google.com/github/keisycascante/QM206/blob/main/clase03-QM206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
x=np.array([3,5,7,9])
x

array([3, 5, 7, 9])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[0]

array([1, 2, 3])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[1]

array([4, 5, 6])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[2,0]

7

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[0,2]

3

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[1,1]

5

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[:,1]

array([2, 5, 8])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[:,2]

array([3, 6, 9])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[0,:]

array([1, 2, 3])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[2,:]

array([7, 8, 9])

In [ ]:
print(x)
print(np.sum(x))
print(np.sum(x*x))

[3 5 7 9]
24
164


In [ ]:
x*x

array([ 9, 25, 49, 81])

In [ ]:
x=([3.4,6.5,8.3,2.4,7.8])
n=len(x)
prom=np.sum(x)/n
print("promedio=", prom)
s2=np.sum((x-prom)**2)/(n-1)
print("varianza=", s2)
des=np.sqrt(s2)
print("desviación estándar=", des)

promedio 5.680000000000001
varianza 6.997000000000002
desviación estándar 2.6451843035977665


In [ ]:
np.sum((x-prom)**2)

27.988000000000007

In [ ]:
x=np.array([3.4,6.5,8.3,2.4,7.8])
y=np.array([4.6,3.2,7.8,9.2,3.5])
sumxy=np.sum(x*y)
sumxy2=np.sum(x*y*y)
print("sumXY=", sumxy)
print("sumXY2=", sumxy2)

sumXY= 150.56
sumXY2= 942.1619999999999


In [ ]:
m=np.sum(x*x)/np.sum(x*y)
print("mn=", m)

mn= 1.25730605738576


In [ ]:
x=np.array([1,2,3,4,5,6])
print(np.cumsum(x))

[ 1  3  6 10 15 21]


In [ ]:
print(np.cumprod(x))

[  1   2   6  24 120 720]


In [ ]:
ka=np.array([2.5E-3, 5.4E-6, 9E-9])
print("ka=", ka)
kt=np.cumprod(ka)
print("kt=", kt)

ka= [2.5e-03 5.4e-06 9.0e-09]
kt= [2.500e-03 1.350e-08 1.215e-16]


In [ ]:
pKa=np.array([1.25, 4.26])
Ka=10**(-pKa)
print(Ka)
Kat=np.cumprod(Ka)
print(Kat)

[5.62341325e-02 5.49540874e-05]
[5.62341325e-02 3.09029543e-06]


Generar números aleatorios

In [ ]:
x=np.random.rand(10)
print(x)
print(np.sum(x))

[0.78594424 0.95677668 0.41051707 0.67323437 0.23342377 0.70164277
 0.56575423 0.73810582 0.89737673 0.448043  ]
6.4108186778412435


In [ ]:
n=np.random.randint(14,size=5)
print("n=", n)

n= [ 3  0  5 11 11]


int= entero

In [ ]:
z=np.random.randint(14, size=50)
print("z=", z)

z= [11  6  4  7  3 10  0 11 12  5  9  0  5  9  0  7  6  4 13  2  7 11 11  5
 10  4  7  4 10 11 11  0  5  7  4 12 12 11  6  2  2  7  4  4 12  3  9 13
  2 10]


In [3]:
pH=5
H=10**(-pH)
n=np.array([2,1,0])
a=H**n
print(a)

pKa=np.array([1.25, 4.26])
Ka=10**(-pKa)
Ka=np.append(1,Ka)
Kat=np.cumprod(Ka)
print(Kat)

[1.e-10 1.e-05 1.e+00]
[1.00000000e+00 5.62341325e-02 3.09029543e-06]


In [5]:
def fracCalc(pKa):
  na=len(pKa)
  Ka=10**(-pKa)
  Ka=np.append(1,Ka)
  Kat=np.cumprod(Ka)
  n=np.arange(na,-1,-1)
  H=10**(-pH)
  sumTotal=np.sum(Kat*a)
  frac=(Kat*a)/sumTotal
  return frac

In [ ]:
pH=8.5
H=10**(-pH)
n=np.array([2,1,0])
a=H**n
print(a)

pKa=np.array([3.25,7.26])
Ka=10**(-pKa)
Ka=np.append(1,Ka)
Kat=np.cumprod(Ka)
print(Kat)
sumTotal=np.sum(Kat*a)
print("sumTotal=",sumTotal)
frac=(Kat*a)/sumTotal
print(frac)

[1.00000000e-17 3.16227766e-09 1.00000000e+00]
[1.00000000e+00 5.62341325e-04 3.09029543e-11]
sumTotal= 3.268124373517484e-11
[3.05985907e-07 5.44128438e-02 9.45586850e-01]


In [ ]:
pHs=np.arange(1,14,0.5)
for pH in pHs:
  H=10**(-pH)
  n=np.array([3,2,1,0])
  a=H**n
  pKa=np.array([2.15,7.2,12.15])
  Ka=10**(-pKa)
  Ka=np.append(1,Ka)
  Kat=np.cumprod(Ka)
  sumTotal=np.sum(Kat*a)
  frac=(Kat*a)/sumTotal
  print(pH,frac)

1.0 [9.33885900e-01 6.61140586e-02 4.17151508e-08 2.95320652e-19]
1.5 [8.17078536e-01 1.82921099e-01 3.64975576e-07 8.17078536e-18]
2.0 [5.85497147e-01 4.14500237e-01 2.61531969e-06 1.85150455e-16]
2.5 [3.08759589e-01 6.91226619e-01 1.37917842e-05 3.08759589e-15]
3.0 [1.23763839e-01 8.76180878e-01 5.52832760e-05 3.91375622e-14]
3.5 [4.27502461e-02 9.57058796e-01 1.90958335e-04 4.27502461e-13]
4.0 [1.39199678e-02 9.85458250e-01 6.21782121e-04 4.40188031e-12]
4.5 [4.43815612e-03 9.93579392e-01 1.98245152e-03 4.43815612e-11]
5.0 [1.40171336e-03 9.92337063e-01 6.26122358e-03 4.43260684e-10]
5.5 [4.37753718e-04 9.80008502e-01 1.95537403e-02 4.37753718e-09]
6.0 [1.32852553e-04 9.40524050e-01 5.93430557e-02 4.20116661e-08]
6.5 [3.72369341e-05 8.33631116e-01 1.66331275e-01 3.72369341e-07]
7.0 [8.66068906e-06 6.13129831e-01 3.86858770e-01 2.73875035e-06]
7.5 [1.49127595e-06 3.33855099e-01 6.66128497e-01 1.49127595e-05]
8.0 [1.93233021e-07 1.36798502e-01 8.63140199e-01 6.11056465e-05]
8.5 [2.131

In [ ]:
pHs

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5])

FUNCIONES

In [6]:
def func1(x,z):
  y=x**2+5*z
  return y


In [7]:
a=func1(8,2)
print(a)

74


In [8]:
def fracCalc(pKa,pH):
  na=len(pKa)
  Ka=10**(-pKa)
  Ka=np.append(1,Ka)
  Kat=np.cumprod(Ka)
  n=np.arange(na,-1,-1)
  H=10**(-pH)
  a=H**n
  sumTotal=np.sum(Kat*a)
  frac=(Kat*a)/sumTotal
  return frac

In [9]:
pKas=np.array([8.28,12.3,15.0])
pHs=np.arange(1,14,0.5)
for pH in pHs:
    print(fracCalc(pKas,pH))

[9.99999948e-01 5.24807433e-08 2.63026785e-19 2.63026785e-33]
[9.99999834e-01 1.65958663e-07 2.63026756e-18 8.31763633e-32]
[9.99999475e-01 5.24807185e-07 2.63026661e-17 2.63026661e-30]
[9.99998340e-01 1.65958415e-06 2.63026363e-16 8.31762391e-29]
[9.99994752e-01 5.24804706e-06 2.63025419e-15 2.63025419e-27]
[9.99983404e-01 1.65955937e-05 2.63022434e-14 8.31749967e-26]
[9.99947522e-01 5.24779919e-05 2.63012996e-13 2.63012996e-24]
[9.99834069e-01 1.65931153e-04 2.62983155e-12 8.31625756e-23]
[9.99475468e-01 5.24532182e-04 2.62888833e-11 2.62888833e-21]
[9.98343162e-01 1.65683724e-03 2.62591007e-10 8.30385674e-20]
[9.94779321e-01 5.22067609e-03 2.61653621e-09 2.61653621e-18]
[9.83675032e-01 1.63249420e-02 2.58732895e-08 8.18185254e-17]
[9.50135909e-01 4.98638413e-02 2.49911207e-07 2.49911207e-15]
[8.57661384e-01 1.42336360e-01 2.25587929e-06 7.13371667e-14]
[6.55809193e-01 3.44173557e-01 1.72495393e-05 1.72495393e-12]
[3.75961060e-01 6.23940052e-01 9.88878342e-05 3.12710789e-11]
[1.59981

In [10]:
na=3
np.arange(na,-1,-1)

array([3, 2, 1, 0])